import Footer from "@/components/footer";
import "bootstrap/dist/css/bootstrap.min.css";
import "../global.scss";
import Header from "@/components/header";
import { Container } from "react-bootstrap";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
        <Container>{children}</Container> 
       
      </body>
    </html>
  );
}
